### ISSUE TITLE
Free up some disk space on TPP

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/sysadmin#103]
We're using up disk at the rate (very roughly) of 0.5T a month. We're currently at 1.5T free. Last month, at one point we temporarily used up 1.5T, so if that happens again we might have a problem. We should come up with a plan to free up some space in the short term, so that our users can continue running jobs while we're working on SACRO.

One possible solution might be to help the researchers responsible for [this workspace](https://jobs.opensafely.org/university-of-manchester/brit-antibiotic-research/ab_covid_rf/16976/) to move over to compressed CSVs.

⤵ https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner-metrics/result/w5QwUNgufv8/a/FBMKE4c9T7f/Free-disk-space?omitMissingValues

🧵 https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1680790555418359

**Comment by lucyb** [comment]
Is this useful? https://github.com/opensafely-core/job-runner/issues/298#issuecomment-1115926202

**Comment by madwort** [comment]
notes from call with Simon

---

* projects are flagged as archived on job-server
  * then refuse to run
* have lots of data in /srv/*_privacy
* archived data in /archive/archived_workspaces
* archive script:
  * creates a compressed file in /archive from files in /srv/*/workspace_name
  * verifies the archive file
  * deletes the original files
  * has some prompts
  * should be run as jobrunner user
* archive file format
  * were originally done with xz
  * now done with gz because small increase in file size but big decrease in compression time
  * some archives are still xz, both are supported for reading
* file permissions
  * should check file permissions for jobrunner user
  * under the hood files may be mounted into the linux VM via SMB using Simon's personal creds
    * maybe in /etc/smb* ?
* list of archived workspaces
  * chase people to archive more workspaces
     * internal - @madwort to do?
     * Bristol - @bloodearnest to do
  * url on job-server that generates list? (ask @ghickman)
  * grab direct from the db
  * job-server/vms is a possible route for getting a file into the VM
* doing the archiving 
  * use shell scripts (grep/bash) to run the archive script on all necessary workspaces

**Comment by madwort** [comment]
tweaked some bugs in the archive script & successfully archived one old workspace (brit_cc_v2). Have a list on the vm of workspaces that are flagged as archive in job-server but not archived on the vm, some low-hanging fruit ready to archive next time I'm working on this (inc. a 300GB Bristol workspace).

**Comment by madwort** [comment]
note to self 
```bash
for i in `cat workspaces.txt`; do sudo du --max-depth 0 -h /srv/high_privacy/workspaces/$i ; done > myfile.txt
```

**Comment by madwort** [comment]
some statistics, presented at the weekly meeting:

* high privacy disk
  * disk is 12TB
  * 11TB is currently used by 290 workspaces
  * largest is 1.6TB
* archive disk
  * disk is 500GB
  * 222GB is currently used by 87 workspaces
  * => average size 2.5GB
  * largest is 20GB
* running out of space on high privacy
  * we're typically adding roughly 100GB/wk or 500GB/month
  * we need a buffer of up to 800GB
  * we currently have 1.1TB available, giving us 300GB until we potentially hit an issue
* running out of space on /archive
  * we have space on /archive for maybe another 100 workspaces
  * 50 projects are available for archiving now
  * we may run out of space on /archive before contracts are signed in Nov 2023  

(at least) two potentially interesting suggestions from others to follow up:

* are measures files eating a lot of disk space?
  * more recent versions stream the data, but older versions dump it to disk
  * easy to eat a lot of disk space without really realising it
  * @evansd to attempt to provide a regex / shell expansion to make this visible
* as a project develops, do actions & ouputs get renamed?
  * this could leave duplicate copies of files under different names

**Comment by madwort** [comment]
## measures files

getting some stats on the autogenerated measures outputs:

```bash
tpp:/srv/high_privacy/workspaces/workspace1/output$ du -sbch input*20[12][7890123]*
```

there is some usage, but it's actually not a huge issue relative to other issues. Top 5:

asthma_sro 133G
the_effects_of_covid-19_on_doac_prescribing 161G
qof-blood-pressure 109G
pincer-measures 92G
opioids_covid_research 89G

then another 10-15 around the 10-20GB mark, then some others smaller than this. Doesn't seem like it will make an appreciable difference in the short term to tidy these up.

**Comment by madwort** [comment]
have manually archived a selection of workspaces. It's worth mentioning that workspaces that are already using gzipped csv files essentially do not compress when archiving - e.g. hosp_pred was 12GB as the workspace & is still 12GB as the archive. Given that the disk space is running low on /archive as well as /workspaces, the best approach seems to be to archive the largest (& presumably mostly uncompressed) workspaces - and only archive the smaller workspaces (& presumably mostly compressed) workspaces if we still have space after that.

**Comment by madwort** [comment]
one thing I just noticed is - I just archived `comparative-ve-research_main` using the current gz compression, but there was already an xz archive. We switched to gzip because it's significantly faster than xz, and when the switch was made there was time pressure on the archiving job - however it doesn't do as good a job at compression. It's interesting to see (what I think is) a direct comparison - 18GB for xz vs 41G for gzip. If we get into a tight corner it might be worth re-compressing some of the gzip archives into xz (but a bigger `/archive` would be my preference...)

**Comment by madwort** [comment]
I’ve archived 8 workspaces / 1TB of studies, focusing on the largest ones. Current status:


## workspace disk

* 9.5TB used (up from ~11.5TB - numbers are approx because active workspaces are constantly changing)
* 282 workspaces

## archive disk

* 387GB used (up from 222GB)
* 95 workspaces

## available to archive

* 671GB (down from 1.6TB)
* 42 workspaces (down from 50)

**Comment by madwort** [comment]
some sample archives, showing variation in compression ratio:

* hosp_pred 12G on workspace -> 12G archive file
* amr-uom-brit-main 14G on workspace -> 14G archive file
* gastrointestinal-coxipw3 98G on workspace -> 15G archive file
* post-covid-mentalhealth 303G on workspace  -> 31G archive file

**Comment by madwort** [comment]
attempted to archive covid-vaccine-effectiveness-research_positivity (77GB) with 44GB available  - operation failed due to insufficient disk space.

**Comment by madwort** [comment]
archived a couple more smaller ones, final tally is 20GB free on /archive , still 40-odd workspaces that could be archived.

**Comment by madwort** [comment]
putting this in review as I think I've done all I can for now, pending other tickets

**Comment by bloodearnest** [comment]
The [job-runner code](https://github.com/opensafely-core/job-runner/blob/5163681e9332f7845672fe4b83743161a634e3a1/jobrunner/executors/local.py#L80) handles either compression format, in terms of detecting an archived repo.

We originally using .xz, but it was very slow, and we had a lot of things to archive and time pressure (downtime), so we switched to .gz

The archive script p/robably needs fixing to check for either extension?

Also, we can use xz for these perhaps, if we're less time pressured. We could also re-compress the gz ones to xz if we wanted?

**Comment by madwort** [comment]
> Also, we can use xz for these perhaps, if we're less time pressured.

Yes, I think that is worth considering.

> We could also re-compress the gz ones to xz if we wanted?

Yes, I thought about that, although (finger in the air) that might apply to maybe ~250GB of files, so we might hope to save ~125GB of space, so I currently think there are lower, juicier fruit elsewhere.

**Comment by madwort** [comment]
if we can do https://github.com/opensafely-core/sysadmin/issues/108 then we can do more on this ticket

**Comment by madwort** [comment]
more workspaces were archived, for ref free space currently:

/archive  - 2147208048 free
/         - 2503768664 free
total     - 4650976712 free
honeycomb - 4650767098 free (slight time lag)

Honeycomb low disk alert threshold modified to 2.8TB to account for the fact that the measurement includes the space on /archive.

We have done enough for now, we can review in the future when we next run out of space & need to free some room.
