### ISSUE TITLE
Avoid the low memory alert triggering repeatedly when the TPP backend is unavailable

### ISSUE THREAD

**Issue by CLStables** [opensafely-core/sysadmin#104]
I noticed that on the 4th and 12th April we had a lot of alerts triggered for "very low free memory". I believe this was because the TPP backend was briefly unavailable (that alert also, correctly, triggered).

It would be better if the[ low memory alert](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner-metrics/triggers/eBESjfhL2L5) behaved more like the[ low disk space](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner-metrics/triggers/Jash9HurnkE) alert and didn't trigger when the system is unavailable.

There are obvious differences in the setup of the two triggers, but I'm not sure why those settings have been chosen and don't want to accidentally change something important.

**Comment by madwort** [comment]
It may have been set this way because low memory could itself cause the system to become unavailable. However, this kind of alert is only useful if it doesn't give false positives - so given that we've just experienced a false positive let's tweak it & see how it goes. If we encounter a situation where we are slow to spot an outage that is system unavailable due to low memory, we could consider tweaking it back. 

To do this, I've added a "where exists" clause, so that it won't trigger. The other difference between the two settings is the "nag" box ("Send an alert every time threshold is met") which I'm going to leave as-is for now, because if have critically low memory on this machine we really should be doing something about it.
