### ISSUE TITLE
Expose route to honeycomb from backends

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#69]
We need a way to ship honeycomb traffic safely from backends.

We should probably evaluate their go proxy, which has options.

Initially we will likely want to run single proxy on dokku2, and later *possibly* a per-backend proxy as well.

**Acceptance Criteria**
* OTel Trace information emitted from job-runner can be sent to Honeycomb
* playbook for setup

**Comment by madwort** [comment]
Working on running the otel/opentelemetry-collector:0.54.0 docker image on dokku2 as a gateway. 
Testing using a simple python script sending telemetry to the collector and onwards to honeycomb, currently having SSL issues.

**Comment by madwort** [comment]
ssl/grpc/https stuff:

The docker image by default only exposes grpc without SSL, the client seems to expect grpc with SSL. As far as I can tell, dokku is only usefully going to proxy https (with ssl) for us rather than grpc with ssl, so switch to using https instead. 

If we instruct it to proxy 443 to the otel http port (4318) it complains that it's missing an SSL, but if we use `dokku letsencrypt` it complains that we're not proxying 443. So, use `dokku ssl` to create a self-signed cert, then `dokku proxy 443:4318`, and then you can use `dokku letsencrypt` to install a better certificate.

configuration:

The deployed otel-collector gateway's pipeline should listen for otel on grpc & http and forward to honeycomb otlp (otel) as well as console logging.  

local testing:

The simple demo python app with telemetry can connect to the deployed gateway, send spans and the spans are observed on the console logging with `docker container attach`, however I'm still not seeing anything received by honeycomb for unknown reason.

**Comment by madwort** [comment]
Ok, I was convinced my config file was being used, but it actually wasn't... :sigh: So, it now works as an open relay. Now I'm investigating options for authorising clients that want to send to the relay. There's a few options in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor - have started with basicauthextension, which may be all we need. The receiver side seems easy to setup, I'm currently trying to convince the otel python lib to send the authorisation info. These authentication extensions seem more geared to facilitating collectors to talk to each other securely. If we had tailscale we could just restrict network access & run an open relay...?

**Comment by bloodearnest** [comment]
Can you add to OTEL_EXPORTER_OTLP_HEADERS env var in the python client?

```
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=BASICAUTHTOKEN"
```

If you can't easily have the collector inject the x-honeycomb-team=BLAH, you should be able to specify multiple headers via the env var, AIUI, with comma separation.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specifying-headers-via-environment-variables.

Another option is pass the headers directly when you add the OTLPSpanProcessor: https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L55

**Comment by lucyb** [comment]
(Note: I added some acceptance criteria. Please edit if you feel it's appropriate)

**Comment by madwort** [comment]
ugh, after far too much back & forth, basic auth is working - switching from inlining the password in the yaml to loading it from a file did the trick :sigh:

**Comment by madwort** [comment]
using 
```
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic%20........................"
```
in the manner of https://www.debugbear.com/basic-auth-header-generator 
baggage encoding, `=` is allowed but ` ` is not, etc

**Comment by madwort** [comment]
data is flowing successfully from job-runner, playbook is here: https://github.com/ebmdatalab/sysadmin/pull/227
